name: Temporary SSH VPS

on:
  workflow_dispatch:

jobs:
  ssh-vps:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # حوالي 6 ساعات
    steps:
      - name: Install & Configure SSH
        run: |
          sudo apt update -y
          sudo apt install -y openssh-server
          sudo systemctl enable ssh
          sudo systemctl start ssh
          echo "root:admin@123" | sudo chpasswd
          echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config
          sudo systemctl restart ssh
          echo "✅ SSH user: root | pass: admin@123"

      - name: Keep VPS Alive
        run: |
          while true; do
            echo "[$(date)] VPS running..."
            sleep 300
          done
